name: CI

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
    paths-ignore: [ '**.md' ]
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths-ignore: [ '**.md' ]

jobs:
  build:
    name: ${{ matrix.os }} • ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: gcc
#          - os: ubuntu-latest
#            cc: clang
          - os: macos-latest
            cc: clang
          - os: windows-latest
            cc: msvc

    steps:
      - uses: actions/checkout@v4

      - name: Configure (POSIX)
        if: matrix.os != 'windows'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo
        env:
          CC: ${{ matrix.cc }}

      - name: Build (POSIX)
        if: matrix.os != 'windows'
        run: cmake --build build --config RelWithDebInfo

      - name: Test (POSIX)
        if: matrix.os != 'windows'
        run: ctest --test-dir build --output-on-failure

      - name: Configure (MSVC x64)
        if: matrix.os == 'windows'
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build (MSVC)
        if: matrix.os == 'windows'
        run: cmake --build build --config RelWithDebInfo

      - name: Test (MSVC)
        if: matrix.os == 'windows'
        run: ctest --test-dir build -C RelWithDebInfo --output-on-failure
